/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppAlert: typeof import('./src/components/common/AppAlert.vue')['default']
    AppButton: typeof import('./src/components/common/AppButton.vue')['default']
    AppCard: typeof import('./src/components/common/AppCard.vue')['default']
    AppCheckbox: typeof import('./src/components/common/AppCheckbox.vue')['default']
    AppIcon: typeof import('./src/components/common/AppIcon.vue')['default']
    AppInput: typeof import('./src/components/common/AppInput.vue')['default']
    AppLoader: typeof import('./src/components/common/AppLoader.vue')['default']
    AppModal: typeof import('./src/components/common/AppModal.vue')['default']
    AppSelect: typeof import('./src/components/common/AppSelect.vue')['default']
    AppTextarea: typeof import('./src/components/common/AppTextarea.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
