# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration file names; The default value is %%(rev)s_%%(slug)s
# Uncomment string line to use a different format
# file_template = %%(rev)s_%%(slug)s_%%(year)d_%%(month).2d_%%(day).2d_%%(hour).2d%%(minute).2d-%%(second).2d

# sys.path path, used relative to the current working directory
# prepend = /path/to/project

# the output encoding used when writing migration files
# output_encoding = utf-8

# database URL
sqlalchemy.url = driver://user:pass@db:5432/dbname

# Logging configuration
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
