"""doc attachment

Revision ID: 00e9e6ee9e59
Revises: d9178cc90e3d
Create Date: 2026-09-25 10:50:20.227653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '00e9e6ee9e59'
down_revision: Union[str, Sequence[str], None] = 'd9178cc90e3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_attachment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False, comment='Исходное имя файла'),
    sa.Column('stored_name', sa.String(length=255), nullable=False, comment='Уникальное имя в хранилище'),
    sa.Column('file_size', sa.BigInteger(), nullable=False, comment='Размер файла в байтах'),
    sa.Column('mime_type', sa.String(length=100), nullable=False, comment='MIME-тип файла'),
    sa.Column('file_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_name')
    )
    op.create_index(op.f('ix_project_attachment_project_id'), 'project_attachment', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_attachment_project_id'), table_name='project_attachment')
    op.drop_table('project_attachment')
    # ### end Alembic commands ###
