"""add foreign key to project in card

Revision ID: 2c9daf77d449
Revises: eb702c7e5517
Create Date: 2026-09-10 15:53:58.002016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c9daf77d449'
down_revision: Union[str, Sequence[str], None] = 'eb702c7e5517'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'project_card', 'project', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_card', type_='foreignkey')
    # ### end Alembic commands ###
