"""add last update

Revision ID: 42887aba2a78
Revises: 8aee1b79e1d7
Create Date: 2026-09-10 16:39:03.966893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42887aba2a78'
down_revision: Union[str, Sequence[str], None] = '8aee1b79e1d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_board', sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('task_board', sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_board', 'last_activity_at')
    op.drop_column('project_board', 'last_activity_at')
    # ### end Alembic commands ###
