"""empty message

Revision ID: 433b03e832a5
Revises: 653f6c063aab
Create Date: 2026-10-01 16:31:31.217828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '433b03e832a5'
down_revision: Union[str, Sequence[str], None] = '653f6c063aab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('sab_task_users_employee_id_fkey'), 'sab_task_users', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('sab_task_users_employee_id_fkey'), 'sab_task_users', 'user_role', ['employee_id'], ['employee_id'])
    # ### end Alembic commands ###
