"""coscade

Revision ID: 653f6c063aab
Revises: ccfcbf3abf52
Create Date: 2026-10-01 16:22:32.028387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '653f6c063aab'
down_revision: Union[str, Sequence[str], None] = 'ccfcbf3abf52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('project_data_project_id_fkey'), 'project_data', type_='foreignkey')
    op.create_foreign_key(None, 'project_data', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('sab_task_status_id_fkey'), 'sab_task', type_='foreignkey')
    op.create_foreign_key(None, 'sab_task', 'task_status', ['status_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('sab_task_users_sub_task_id_fkey'), 'sab_task_users', type_='foreignkey')
    op.create_foreign_key(None, 'sab_task_users', 'sab_task', ['sub_task_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('task_status_id_fkey'), 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'task_status', ['status_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('task_board_project_id_fkey'), 'task_board', type_='foreignkey')
    op.create_foreign_key(None, 'task_board', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('task_board_users_board_id_fkey'), 'task_board_users', type_='foreignkey')
    op.drop_constraint(op.f('task_board_users_employee_id_fkey'), 'task_board_users', type_='foreignkey')
    op.create_foreign_key(None, 'task_board_users', 'task_board', ['board_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('task_column_board_id_fkey'), 'task_column', type_='foreignkey')
    op.create_foreign_key(None, 'task_column', 'task_board', ['board_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('task_data_task_id_fkey'), 'task_data', type_='foreignkey')
    op.create_foreign_key(None, 'task_data', 'task', ['task_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('task_users_task_id_fkey'), 'task_users', type_='foreignkey')
    op.create_foreign_key(None, 'task_users', 'task', ['task_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_users', type_='foreignkey')
    op.create_foreign_key(op.f('task_users_task_id_fkey'), 'task_users', 'task', ['task_id'], ['id'])
    op.drop_constraint(None, 'task_data', type_='foreignkey')
    op.create_foreign_key(op.f('task_data_task_id_fkey'), 'task_data', 'task', ['task_id'], ['id'])
    op.drop_constraint(None, 'task_column', type_='foreignkey')
    op.create_foreign_key(op.f('task_column_board_id_fkey'), 'task_column', 'task_board', ['board_id'], ['id'])
    op.drop_constraint(None, 'task_board_users', type_='foreignkey')
    op.create_foreign_key(op.f('task_board_users_employee_id_fkey'), 'task_board_users', 'user_role', ['employee_id'], ['employee_id'])
    op.create_foreign_key(op.f('task_board_users_board_id_fkey'), 'task_board_users', 'task_board', ['board_id'], ['id'])
    op.drop_constraint(None, 'task_board', type_='foreignkey')
    op.create_foreign_key(op.f('task_board_project_id_fkey'), 'task_board', 'project', ['project_id'], ['id'])
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key(op.f('task_status_id_fkey'), 'task', 'task_status', ['status_id'], ['id'])
    op.drop_constraint(None, 'sab_task_users', type_='foreignkey')
    op.create_foreign_key(op.f('sab_task_users_sub_task_id_fkey'), 'sab_task_users', 'sab_task', ['sub_task_id'], ['id'])
    op.drop_constraint(None, 'sab_task', type_='foreignkey')
    op.create_foreign_key(op.f('sab_task_status_id_fkey'), 'sab_task', 'task_status', ['status_id'], ['id'])
    op.drop_constraint(None, 'project_data', type_='foreignkey')
    op.create_foreign_key(op.f('project_data_project_id_fkey'), 'project_data', 'project', ['project_id'], ['id'])
    # ### end Alembic commands ###
