"""empty message

Revision ID: fbf567da3482
Revises: 7d2c908271db
Create Date: 2026-10-01 16:41:39.045679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbf567da3482'
down_revision: Union[str, Sequence[str], None] = '7d2c908271db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('task_status_id_fkey'), 'task', type_='foreignkey')
    op.drop_constraint(op.f('task_column_id_fkey'), 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'task_status', ['status_id'], ['id'])
    op.create_foreign_key(None, 'task', 'task_column', ['column_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key(op.f('task_column_id_fkey'), 'task', 'task_column', ['column_id'], ['id'])
    op.create_foreign_key(op.f('task_status_id_fkey'), 'task', 'task_status', ['status_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
